### ISSUE TITLE
Maybe better

### ISSUE THREAD

**Issue by y11en** [mr21/strsplit.c#2]
```

char** strsplit( const char* s, const char* del , int* n);

```

`n` is the number of return ` char* [n] `

**Comment by mr21** [comment]
Hi @y11en,

This is interesting, to not complexify the prototype by adding an extra `NULL` for the basic usage, i could add another function instead.

But what is the need of having the size of the array anyway?

**Comment by y11en** [comment]
Hi @mr21 ,

I haven’t considered the actual use yet, but I think there is no need to loop through it if the size is known

E.g

"I think something need to do"

if (n > 5)
{
    // char* [n-1]  is "do"
    // char* [n-2]  is "to"
}
So, i don't need to loop to get it.

**Comment by mr21** [comment]
This was a good idea, so i made a `strsplit_count` version with a `size_t` instead of an int (like discussed in the previous #1 issue).

> So, i don't need to loop to get it.

Funny because it's what i was doing in the tests when i use `qsort` who ask for the number of items, so now the tests are simpler, thx 👍
